### ISSUE TITLE
Should we not remove .git from sciserver_cookbooks?

### ISSUE THREAD

**Issue by trjaffe** [sciserver/sciserver-compute-images#25]
https://github.com/sciserver/sciserver-compute-images/blob/163b3296e7a8f10034d34775f3d7d4eeb7001644/heasarc/heasarc/Dockerfile#L96

If we don't remove the .git, then users could just git pull to get any updates without us having to rebuild the heasarc image.  @zoghbi-a ?

**Comment by zoghbi-a** [comment]
This has been fixed for a while. Please close the issue.
