### ISSUE TITLE
Add Emacs as an editor in HEASoft images

### ISSUE THREAD

**Issue by CraigMarkwardt** [sciserver/sciserver-compute-images#31]
Hi, could you add emacs as an editor to the HEASoft images?  Thanks!

**Comment by trjaffe** [comment]
@zoghbi-a

**Comment by zoghbi-a** [comment]
@CraigMarkwardt, emacs is now available in the latest image: HEASARCv6.33.1. If you are already running that image, you may want to create a new one to pick up the updates.

**Comment by CraigMarkwardt** [comment]
Thanks

**Comment by esabol** [comment]
@CraigMarkwardt , please close the issue.

**Comment by CraigMarkwardt** [comment]
Close
